nstance_type = "t2.large"
key_name = ""
ami = "ami-0ff760d16d9497662"
vpc_id = "vpc-908caaf6"
user = "centos"  # Centos7 image
ssh_key_location = "/ssh_keys/app_rsa" # Iport public key pair to AWS as "terraform"
zone_id = "Z32OHGRMBVZ9LR" # Hosted DNS zone and ID was added here
domain = "acirrustech.com"
region = "eu-west-1"
